//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FootStat.Domain.Abstract;

namespace FootStat.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match : IEntitie 
    {
        public Match()
        {
            this.MatchDetails = new HashSet<MatchDetail>();
        }
    
        public int Id { get; set; }
        public int TourneyId { get; set; }
        public System.DateTime Date { get; set; }
        public string Tour { get; set; }
        public int FirstCommandId { get; set; }
        public int SecondCommandId { get; set; }
        public int ResultId { get; set; }
        public int ScoreFirstCommandId { get; set; }
        public int ScoreSecondCommandId { get; set; }
        public Nullable<bool> TopMatch { get; set; }
        public int ForecastId { get; set; }
        public int SeasonId { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Command Command1 { get; set; }
        public virtual Forecast Forecast { get; set; }
        public virtual Result Result { get; set; }
        public virtual Tourney Tourney { get; set; }
        public virtual ICollection<MatchDetail> MatchDetails { get; set; }
    }
}
