//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FootStat.Domain.Abstract;

namespace FootStat.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class MatchDetail : IEntitie
    {
        public int Id { get; set; }
        public int MatchId { get; set; }
        public int Min { get; set; }
        public int DetailTypeId { get; set; }
        public int CommandId { get; set; }
        public string Person { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual Match Match { get; set; }
        public virtual MatchDetailType MatchDetailType { get; set; }
    }
}
