//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FootStat.Domain.Abstract;

namespace FootStat.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportStatEntities : DbContext, IDBContext {
        public SportStatEntities()
            : base("name=SportStatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public DbSet<Command> Commands { get; set; }
        public DbSet<Forecast> Forecasts { get; set; }
        public DbSet<Match> Matches { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<Tourney> Tourneys { get; set; }
        public DbSet<TournamentTable> TournamentTables { get; set; }
        public DbSet<MatchDetail> MatchDetails { get; set; }
        public DbSet<MatchDetailType> MatchDetailTypes { get; set; }
    }
}
