//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FootStat.Domain.Abstract;

namespace FootStat.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Command : IEntitie
    {
        public Command()
        {
            this.Matches = new HashSet<Match>();
            this.Matches1 = new HashSet<Match>();
            this.TournamentTables = new HashSet<TournamentTable>();
            this.MatchDetails = new HashSet<MatchDetail>();
        }
    
        public int Id { get; set; }
        public int TourneyId { get; set; }
        public string CommandNameEn { get; set; }
        public string ShortNameEn { get; set; }
        public string CommandNameRu { get; set; }
        public string ShortNameRu { get; set; }
        public Nullable<int> Rate { get; set; }
        public bool Actual { get; set; }
        public string LogoUrl { get; set; }
    
        public virtual Tourney Tourney { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<Match> Matches1 { get; set; }
        public virtual ICollection<TournamentTable> TournamentTables { get; set; }
        public virtual ICollection<MatchDetail> MatchDetails { get; set; }
    }
}
