//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FootStat.Domain.Abstract;

namespace FootStat.Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Tourney : IEntitie
    {
        public Tourney()
        {
            this.Commands = new HashSet<Command>();
            this.Matches = new HashSet<Match>();
            this.TournamentTables = new HashSet<TournamentTable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortNameRu { get; set; }
        public int CountComannds { get; set; }
        public string LogoUrl { get; set; }
        public string CountryFlag { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<Command> Commands { get; set; }
        public virtual ICollection<Match> Matches { get; set; }
        public virtual ICollection<TournamentTable> TournamentTables { get; set; }
    }
}
